### ISSUE TITLE
Course Location

### ISSUE THREAD

**Issue by Jenjop** [jogplus/zotcourse#1]
Does not display course location.

**Comment by jogplus** [comment]
Hi! Please attach a screenshot and describe the steps that led you to this issue.

**Comment by Jenjop** [comment]
![image](https://user-images.githubusercontent.com/30666432/46770768-9ec23d00-cca5-11e8-98be-fc98b65068d6.png) Input classes and the location that the class is held is not displayed.

**Comment by jogplus** [comment]
Please click on the event in order to see additional information like course location. Additionally, it seems like you imported your schedule from Antplanner. Please note that not all the information will be a available in the popover due to the limitations of Antplanner. Let me know if you have any other issues or questions!
