### ISSUE TITLE
Mobile Glitch

### ISSUE THREAD

**Issue by HeroVincent** [jogplus/zotcourse#2]
When clicking on any of the top tabs such as Save or Load, on mobile, the pop-up only last for a split second and then disappears. Thus not allowing me to type anything. I am not sure if maybe it's just my phone. Thank you!

**Comment by jogplus** [comment]
Hi! Could you tell me what device you are using and what browser? Currently mobile isn't really supported, but I can try looking into it.

**Comment by HeroVincent** [comment]
Hey! I am using a OnePlus 5t and using the Google Chrome browser app.

**Comment by ekureina** [comment]
Can reproduce on Original Google Pixel Standard Size with Google Chrome 70.0.3538.80 on the latest updated version of Android 9.0.0. The bug is in input text pop-up, the other buttons and info pop-up work fine. Chrome is detecting input, as it brings up the keyboard. This occurs whether or not I am running the "Desktop Version" of the site.

**Comment by jogplus** [comment]
Okay I have just published a workaround for this. It should now prompt your device for the username without having to use the popover on mobile. Let me know if this fixes it for you and thanks for reporting it!
