### ISSUE TITLE
Unable to remove Online/TBA classes from the list

### ISSUE THREAD

**Issue by shengyuan-lu** [jogplus/zotcourse#32]
Currently I am unable to remove online/TBA classes once I added it to the list. For non-online/tba classes I can just click the block and click remove, but with tba classes there's no block available. For W23 quarter, you may use MGMT 107 to test it. Not sure if I misunderstood the features, but certainly not very obvious.

**Comment by jogplus** [comment]
Hi Shengyuan, there should be a popup that appears when adding an online/TBA course which indicates you can view the course using the List button. From there you can click on the course in the list to remove it. 
![Screenshot 2022-11-13 at 3 02 29 PM](https://user-images.githubusercontent.com/24497772/201544721-395c4b17-8c0b-4a8f-adb5-bd57f2759cac.png)

I agree that it would be more ideal for it to appear somewhere on the calendar view so that its not missed, but I'm not planning to make any changes to Zotcourse at this time.
