### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by sbondoc** [jogplus/zotcourse#4]
The attached screenshot is all you see when you go to Zotcourse on desktop. Issue applies to mobile as well. The course search dialog appears if you scroll down but the actual schedule display appears to be bugged.

Size button also gets stuck after initial toggle.

![10](https://user-images.githubusercontent.com/42726060/48036331-b4981600-e11c-11e8-87a2-839e5366b650.png)

**Comment by jogplus** [comment]
It turns out that the one of my dependencies (split.js hosted at https://unpkg.com/split.js/split.min.js) is currently down or moved. As a workaround I have added the split.js file to the project so that it does not have to rely on unpkg. This might take several minutes for the html cache to expire and for you to see the change. Thank you for reporting this!
